version: "3.7"
services:
  db:
    image: mysql:8.0.26
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
      - MYSQL_DATABASE=twiffer
      - LANG=C.UTF-8
    volumes:
      - my-datavolume:/var/lib/mysql

volumes:
  my-datavolume:
    
